package com.pbl4.studentweb.common.catalog;

// Labels follow the NSO ethnic-group catalog, including foreign and unknown categories.
public enum Ethnicity {
    KINH("Kinh"),
    TAY("Tày"),
    THAI("Thái"),
    HOA("Hoa"),
    KHO_ME("Khơ-me"),
    MUONG("Mường"),
    NUNG("Nùng"),
    HMONG("HMông"),
    DAO("Dao"),
    GIA_RAI("Gia-rai"),
    NGAI("Ngái"),
    E_DE("Ê-đê"),
    BA_NA("Ba na"),
    XO_DANG("Xơ-Đăng"),
    SAN_CHAY("Sán Chay"),
    CO_HO("Cơ-ho"),
    CHAM("Chăm"),
    SAN_DIU("Sán Dìu"),
    HRE("Hrê"),
    MNONG("Mnông"),
    RA_GLAI("Ra-glai"),
    XTIENG("Xtiêng"),
    BRU_VAN_KIEU("Bru-Vân Kiều"),
    THO("Thổ"),
    GIAY("Giáy"),
    CO_TU("Cơ-tu"),
    GIE_TRIENG("Gié Triêng"),
    MA("Mạ"),
    KHO_MU("Khơ-mú"),
    CO("Co"),
    TA_OI("Tà-ôi"),
    CHO_RO("Chơ-ro"),
    KHANG("Kháng"),
    XINH_MUN("Xinh-mun"),
    HA_NHI("Hà Nhì"),
    CHU_RU("Chu ru"),
    LAO("Lào"),
    LA_CHI("La Chí"),
    LA_HA("La Ha"),
    PHU_LA("Phù Lá"),
    LA_HU("La Hủ"),
    LU("Lự"),
    LO_LO("Lô Lô"),
    CHUT("Chứt"),
    MANG("Mảng"),
    PA_THEN("Pà Thẻn"),
    CO_LAO("Co Lao"),
    CONG("Cống"),
    BO_Y("Bố Y"),
    SI_LA("Si La"),
    PU_PEO("Pu Péo"),
    BRAU("Brâu"),
    O_DU("Ơ Đu"),
    RO_MAM("Rơ măm"),
    NGUOI_NUOC_NGOAI("Người nước ngoài"),
    KHONG_RO("Không rõ");
    private final String label;
    Ethnicity(String label) { this.label = label; }
    public String label() { return label; }
}
