-- PostgreSQL, manual migration, backend stopped.
-- Prepare nullable faculty links so existing majors can be assigned explicitly.
BEGIN;
CREATE TABLE IF NOT EXISTS public.faculties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_code VARCHAR(20) NOT NULL UNIQUE,
    faculty_name VARCHAR(150) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
ALTER TABLE public.majors ADD COLUMN IF NOT EXISTS faculty_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_majors_faculty_id ON public.majors(faculty_id);
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS number_of_semesters INTEGER;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS total_credits INTEGER;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS required_credits INTEGER;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS elective_credits INTEGER;
COMMIT;
-- Next: create real faculties, map each major.faculty_id, and normalize degree_type.
-- Then execute 003_require_faculties_and_degree_types.sql before starting the backend.
